### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by FrancescJR** [jaroslawgabara/lambda-gin-app#1]
[Oh I am going to have so much fun]

Hey man, awesome repo! you must be a very skilled and good developer. Big tech companies are probably auctioning you.

I just have a doubt. I am Go noob, so don't be harsh with me :crying_cat_face:  I am trying to deploy a lambda with this code, but I think I might need to configure something first maybe?

If I check the cloudwatch logs, I can see all the logs related to the Gyn(tonic) server like this things:

`
[GIN-debug] Listening and serving HTTP on :8080
`
so how can I tell it that hey gyntonic, you are not suppose to start, with an environment variable or something? or am I too lost?

Cheers!

**Comment by jaroslawgabara** [comment]
Hi good Sir!
Thank you so much for your time and appreciation of my indeed great repo! Big companies keep try to conquer my heart by it has always had belong and always will belong to zinio <3 

Forgive me for not documenting this repository properly. Please take a look at app.go, it receives environmental variable called API_TYPE. Set it with a value "LAMBDA" and your application will start as lambda. Feel free to leave a star to this repo, i would really appreciate it.

I hope my reply was helpful. In any further problem feel free to reach me.

Best regards!
Jaroslaw
